### PR TITLE
Fix broken installation of NLopt

### PR DESCRIPTION
**Pull request by chuan-wang**
Tested locally and worked as expected.

### CODE REVIEW

**Comment by ewels** [comment]
Great! Well done for figuring this out @chuan-wang! :)

**Comment by chuan-wang** [comment]
:) Hopefully it will work!

**Comment by ewels** [comment]
Build is passing! 🎉

**Comment by chuan-wang** [comment]
Yeah! Seems like the old version of bowtie2 caused the problem.

**Pull request merged**
